spring.application.name=VivaBot

server.port=8080

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# File Upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# OpenRouter
openai.api.key=${OPENROUTER_API_KEY}
openai.api.url=https://openrouter.ai/api/v1/chat/completions

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.upload.dir=uploads/

spring.web.resources.add-mappings=true
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/

spring.mvc.favicon.enabled=false
logging.level.org.springframework.web.servlet.resource=ERROR

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
